using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assets.Fallout.NET.TES4.SubRecords
{
	/// <summary>
	/// Actor Values
	/// </summary>
	public enum ActorValue
	{
		None = -1,
		Aggression = 00,
		Confidence = 01,
		Energy = 02,
		Responsibility = 03,
		Mood = 04,
		Strength = 05,
		Perception = 06,
		Endurance = 07,
		Charisma = 08,
		Intelligence = 09,
		Agility = 10,
		Luck = 11,
		ActionPoints = 12,
		CarryWeight = 13,
		CriticalChance = 14,
		HealRate = 15,
		Health = 16,
		MeleeDamage = 17,
		DamageResistance = 18,
		PoisonResistance = 19,
		RadResistance = 20,
		SpeedMultiplier = 21,
		Fatigue = 22,
		Karma = 23,
		XP = 24,
		PerceptionCondition = 25,
		EnduranceCondition = 26,
		LeftAttackCondition = 27,
		RightAttackCondition = 28,
		LeftMobilityCondition = 29,
		RightMobilityCondition = 30,
		BrainCondition = 31,
		Barter = 32,
		BigGuns = 33,
		EnergyWeapons = 34,
		Explosives = 35,
		Lockpick = 36,
		Medicine = 37,
		MeleeWeapons = 38,
		Repair = 39,
		Science = 40,
		Guns = 41,
		Sneak = 42,
		Speech = 43,
		Survival = 44,
		Unarmed = 45,
		InventoryWeight = 46,
		Paralysis = 47,
		Invisibility = 48,
		Chameleon = 49,
		NightEye = 50,
		Turbo = 51,
		FireResistance = 52,
		WaterBreathing = 53,
		RadLevel = 54,
		BloodyMess = 55,
		UnarmedDamage = 56,
		Assistance = 57,
		ElectricResistance = 58,
		FrostResistance = 59,
		EnergyResistance = 60,
		EMPResistance = 61,
		Unknown1 = 62,
		Unknown2 = 63,
		Unknown3 = 64,
		Unknown4 = 65,
		Unknown5 = 66,
		Unknown6 = 67,
		Unknown7 = 68,
		Unknown8 = 79,
		Unknown9 = 70,
		Unknown10 = 71,
		IgnoreCrippledLimbs = 72,
		Dehydration = 73,
		Hunger = 74,
		SleepDeprivation = 75,
		Damage = 76,
	}
}
